on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          architecture: "x64"
      - uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          mode: app
          output-file: BridGet.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BridGet
          path: build/BridGet.exe
          include-hidden-files: true
